name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.2', '3.3', '3.4']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install MSYS2 and dependencies
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: false
          install: >-
            git
            base-devel
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libpng
      - name: Build and install libsixel
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          git clone --depth 1 https://github.com/libsixel/libsixel
          cd libsixel
          meson setup build --prefix=/mingw64
          meson compile -C build
          meson install -C build
      - name: Install native libraries (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libturbojpeg libsixel1
      - name: Install native libraries (macOS)
        if: runner.os == 'macOS'
        run: brew install libsixel
      - name: Run the default task
        if: runner.os == 'Windows'
        run: bundle exec rake
        shell: msys2 {0}
      - name: Run the default task
        if: runner.os != 'Windows'
        run: bundle exec rake
        shell: bash

